### ISSUE TITLE
Projects using skan

### ISSUE THREAD

**Issue by CsatiZoltan** [jni/skan#104]
Maybe you could add a list of references that cite your [work](https://peerj.com/articles/4312/). If you want, I can open a PR.
This would increase the "prestige" of *skan* and people browsing this page could see related papers.

**Comment by jni** [comment]
@CsatiZoltan I would certainly welcome such a PR, thank you!

**Comment by CsatiZoltan** [comment]
@jni [On which page](https://jni.github.io/skan/) would you like me to place it?

**Comment by CsatiZoltan** [comment]
@jni PR #106 created.
