### ISSUE TITLE
New skan release?

### ISSUE THREAD

**Issue by constantinpape** [jni/skan#105]
It would be great to get a new skan release. Currently I need to pin numba to <=0.50 because the latest skan release does not include the chaneges for `numba.jitclass` -> `numba.experimental.jitclass`.

**Comment by jni** [comment]
Holy moly, I just saw that I haven't released since Jul 2019! 🤯 Will do. @constantinpape if you are using skan actively do you want maintainer access? No expectation of extra responsibility, just want you to be able to get on with your life rather than be blocked by me. 😅

**Comment by constantinpape** [comment]
> Holy moly, I just saw that I haven't released since Jul 2019! exploding_head Will do.

Thanks!

> @constantinpape if you are using skan actively

I am only using it actively in the sense that I have one function that uses it to extract the graph from a volumetric skeletonized object. (Where it does a perfect job ;)).
So for now I won't need maintainer access, I think once you release now I will be good for the next 2 years ;).

**Comment by jni** [comment]
> I think once you release now I will be good for the next 2 years ;)

Ha! Well, you're set then. ;)
