### ISSUE TITLE
Find nodes and endpoints coordinates

### ISSUE THREAD

**Issue by joooohnny** [jni/skan#132]
Hi guys, 

I would like to find the nodes and endpoints coordinates in my skeleton. It looks to be possible with your library but I don't manage to do it ?

```python
import numpy as np
import matplotlib.pyplot as plt
from scipy import ndimage as ndi
from scipy.signal import argrelextrema
from skimage.morphology import skeletonize
import trimesh
from trimesh.voxel import creation
from skan import skeleton_to_csgraph
from mpl_toolkits.mplot3d import Axes3D  # don't delete this line
from skan import Skeleton, summarize

# 1ere Partie ##########################################################################################################
# ici, on cherche à voxeliser notre objet 3d, c'est à dire à transposer notre objet dans une matrice 3d
# on utilise la librairie trimesh pour cela

mesh = trimesh.load_mesh('../objet 3d/White_Bear.STL')
volume = trimesh.voxel.creation.voxelize(mesh=mesh, pitch=mesh.extents.max() / 128)  # 128=définition de la matrice
# 3D, plus le chiffre est grand, plus la définition sera grande (doit être un multiple de 2)
array = volume.matrix  # matrice 3d de l'objet mais creuse à l'intérieur
object_matrix = ndi.binary_fill_holes(array)  # on remplit l'intérieur de l'objet dans la matrice pour qu'il ne soit
# plus creux

skeleton = skeletonize(object_matrix)  # on obtient le squelette

pixel_graph, coordinates, degrees = skeleton_to_csgraph(skeleton)

branch_data = summarize(Skeleton(skeleton))
branch_data.head()
```

[White_Bear.zip](https://github.com/jni/skan/files/6892812/White_Bear.zip)

I manage to have this, but I don't know how to use those informations to find nodes and endpoints coordinates.
![image](https://user-images.githubusercontent.com/86359014/127317174-ca078501-efce-4e9c-9184-9a2334fa0160.png)

Thanks in advance for your help.

**Comment by joooohnny** [comment]
Another thing I'd like to have is the coordinates of all the voxels by branch. For example, if I have 7 branches, I'd like to have 7 lists. With in the 1st one the coordinates of voxels in the branch 1, in the 2nd one the coordinates of voxels in the branch 2 etc...

Any idea for that ?

Thanks in advance.

**Comment by jni** [comment]
> I manage to have this, but I don't know how to use those informations to find nodes and endpoints coordinates.

The `[image-]coord-src-#` and `[image-]coord-dst-#` contain the start and end point coordinates of each branch, for axes 0, 1, 2. The `image-` prefix indicates the coordinates in pixels, while `coord-src-0` contains the coordinates accounting for the image pixel spacing.

> Another thing I'd like to have is the coordinates of all the voxels by branch.

You want `[skeleton.path_coordinates(i) for i in range(data.shape[0])]`.

https://jni.github.io/skan/api/skan.csr.html#skan.csr.Skeleton.path_coordinates

Let me know if that answers your questions!

**Comment by joooohnny** [comment]
Thank you. This is exactly what I needed. Just some problem for the junction points but I saw you posted an issue about that.
But anyway, you saved me man.

**Comment by siddagra** [comment]
I am having an issue... Whether I use `src` or `dst` coords.. `image-` or otherwise, It often detects junctions as `dst` instead of the endpoints.

How do I specifically get the correct endpoints?

![image](https://user-images.githubusercontent.com/52118936/175804360-69005490-6d9b-43f2-a046-94e48b508493.png)

code:
```
skeleton = cv2.imread("skeletontest.png")[:, :, 1].astype(bool)
pt, degrees = skeleton_to_csgraph(skeleton)
df = summarize(Skeleton(skeleton))
branch1 = df[df['branch-type'] == 1]
endpoints = branch1[["image-coord-dst-0", "image-coord-dst-1"]].values.astype(np.int64)

# plot
# (plotting has to interchange coordinates since the endpoints lists y coordinates first)
for i, pnt in enumerate(endpoints):
    plt.scatter(pnt[1], pnt[0], color="red", s=3)
```
(plotting has to interchange coordinates since the endpoints lists y coordinates first)
