### ISSUE TITLE
Idea: don't collapse junction pixels

### ISSUE THREAD

**Issue by jni** [jni/skan#133]
I've referred people to the junction-handling in skan from the paper's supplementary material more times than I can remember:

https://peerj.com/articles/4312/#supp-1

It's a rather confusing part of the code, and though it is useful, it would be good to have alternatives that preserve each and every pixel in the original skeleton.

One idea: of all the pixels in a junction, only assign *one* to be a junction (how to do that is left as an exercise for the reader). The others get assigned to the incoming paths, and all links to non-junction pixels are removed (ie the degrees are artificially reduced).

**Comment by jni** [comment]
> of all the pixels in a junction, only assign one to be a junction (how to do that is left as an exercise for the reader)

Just had a thought: replace the junction pixels subgraph (which will be something close to a clique) with its minimum spanning tree. This is very well defined and I think it will do the right thing in most if not all cases.

**Comment by kevinyamauchi** [comment]
Next week works for me! Tuesday (Sept 7) or Wednesday (Sept 8) morning (CEST) work best for me.

**Comment by marlene09** [comment]
The 7th works better for me :) talk soon.
