### ISSUE TITLE
Get Junctions or Bifurcation from 3D skeletons

### ISSUE THREAD

**Issue by dzeego** [jni/skan#153]
Hello,

Is is possible to extract degrees of the junctions or bifurcation of 3D skeleton of the vessels?
I saw that this output has been deprecated in the recent releases on Skan.
So what should I do?

Many thanks !

**Comment by jni** [comment]
Hi @dzeego!

Yes I'm in the process of updating the docs and also the API to make these things more obvious. But, specifically, class [`skan.Skeleton`](https://jni.github.io/skan/api/skan.csr.html#skan.csr.Skeleton) contains the degree information for every point of the skeleton. To find the coordinates of bifurcations, do `skeleton.coordinates[skeleton.degrees > 2]`.

... And, I just noticed that there's no such thing as `degrees` in the documentation, even though it's in the object. 🤦 I'll leave this open until I update that.

**Comment by dzeego** [comment]
Hi @jni !

Thank you very much for your reply ! Really helpful :)
I make use of the fact that this issue remains open to ask another question please:
Is it possible to extract the pre-skeletonized diameters (from the original image) directly from the skeleton.
To be more clear, I would like to directly find the different diameters along the skeleton. Is that possible?

Thanks again !

**Comment by jni** [comment]
@dzeego you'll need to do some custom graph work for this. By default, skan does not have any notion of a skeleton "root" node, or bifurcations along a path — skeletons can contain cycles. For example in the original skan paper the skeletons measured are a mesh on the plane.

I think the new skan API I'm working on will let you do this more easily, but basically:

- construct a networkx.Graph or networkx.MultiGraph from skan.summarize() node ID pairs
- Define a node in the graph as the root
- use networkx traversal algorithms to define an edge's distance (in number of hops) from the root
- add that distance to the table
- use the 2D display (skan.draw) or 3D display (see the documentation for displaying skeletons in 3D in napari) functions to display according to that distance.

I hope to update both the API and the docs shortly to make this custom analysis easier. Thanks for your patience!
