### ISSUE TITLE
Bug report: draw.overlay_skeleton_networkx

### ISSUE THREAD

**Issue by dani-lbnl** [jni/skan#161]
Example in https://skeleton-analysis.org/getting_started.html is NOT working. Code below:

from skan import _testdata
g0, c0 = skeleton_to_csgraph(_testdata.skeleton0)

draw.overlay_skeleton_networkx(g0, np.transpose(c0), image=_testdata.skeleton0,
                               axis=axes[0])
draw.overlay_skeleton_networkx(g1, np.transpose(c1), image=_testdata.skeleton1,
                               axis=axes[1])

This is the error:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/networkx/drawing/nx_pylab.py](https://localhost:8080/#) in draw_networkx_nodes(G, pos, nodelist, node_size, node_color, node_shape, alpha, cmap, vmin, vmax, ax, linewidths, edgecolors, label, margins)
    453     try:
--> 454         xy = np.asarray([pos[v] for v in nodelist])
    455     except KeyError as e:

4 frames
KeyError: 2

The above exception was the direct cause of the following exception:

NetworkXError                             Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/networkx/drawing/nx_pylab.py](https://localhost:8080/#) in draw_networkx_nodes(G, pos, nodelist, node_size, node_color, node_shape, alpha, cmap, vmin, vmax, ax, linewidths, edgecolors, label, margins)
    454         xy = np.asarray([pos[v] for v in nodelist])
    455     except KeyError as e:
--> 456         raise nx.NetworkXError(f"Node {e} has no position.") from e
    457 
    458     if isinstance(alpha, Iterable):

NetworkXError: Node 2 has no position.
---------------------------------------------------------------------------
Also, tried with very simple example, does NOT work either:
agraylevel = 255
image = np.zeros((100,100))
image[2:98,5]=agraylevel
image[10,5:15]=agraylevel
image[20,5:25]=agraylevel
image[30,5:15]=agraylevel

**Comment by jni** [comment]
@dani-lbnl Are you on the released (0.10.0) version of skan? If so, could you please upgrade to the main branch? Unfortunately we don't have versioned docs yet so the documentation points to the main branch — where a lot has changed since release.

**Comment by dani-lbnl** [comment]
Thanks @jni - yes, I'm using the latest release (0.10.0) - when you say upgrade, do you mean to v0.10.0rc2 (pre-release)?

**Comment by jni** [comment]
No, I mean something like `pip install git+https://github.com/jni/skan`, which will install the unreleased code changes that generate the docs. Sorry about that — the solution is to properly version the docs, which is part of the plans but not there yet.

**Comment by ns-rse** [comment]
> the solution is to properly version the docs, which is part of the plans but not there yet.

I've used [sphinx-multiversion](https://github.com/Holzhaus/sphinx-multiversion) to achieve this on a few projects recently. I'll see if I can find some time to address this.

**Comment by jni** [comment]
Thanks for bubbling this up @ns-rse. I'd say this can probably be closed now! @dani-lbnl I'd be interested to know whether you were able to get skan working and producing useful results for you. 😊
