### ISSUE TITLE
Speedup idea for finding the graph center for Sholl analysis

### ISSUE THREAD

**Issue by jni** [jni/skan#162]
As noted by @kushaangupta in #148, the automatic skeleton geodesic center-finding is extremely slow. This is because we need to compute the shortest paths for all pairs of pixels in the skeleton.

However, we can speed this up *dramatically* by only considering junctions and endpoints — that is, by only considering the much-reduced junction graph. In scikit-image we don't have this luxury but in skan we do! :tada:

As a preliminary to this, we need to add a way to quickly obtain such a graph in CSR format from the skeleton summary data. Until now, this has always been done manually, but it makes sense for Skan to have a function to generate this.

**Comment by kushaangupta** [comment]
I implemented it just yesterday for my work and it works nicely. I'll open a PR soon. However, I had to convert the csr graph to `networkx.DiGraph` for doing it, and then back to CSR graph.

**Comment by jni** [comment]
That's weird but ok, once you have a PR I can look in more detail. Awesome that you got it working!!!
