### ISSUE TITLE
_build_skeleton_path_graph() incorrectly handles degree-0 nodes in calculation of n_points

### ISSUE THREAD

**Issue by ssavary** [jni/skan#182]
https://github.com/jni/skan/blob/1f71a5b505a7345f1fbc7b52094c2505216fd72b/src/skan/csr.py#L395-L400
https://github.com/jni/skan/blob/1f71a5b505a7345f1fbc7b52094c2505216fd72b/src/skan/csr.py#L406-L409

Degree 0 nodes are mistakenly removed from the set. The correction calculation should be:

```
n_points = (
        graph.indices.size + np.sum(np.max(endpoint_degrees - 1, 0))
        + _buffer_size_offset
        )
```

With very degenerate cases, I get n_points = 0 and memory dumps occur (on linux). The real issue is the n_points computation, not the memory dump, which is only a consequence of bad n_points).

Here is a matrix that triggers the bug (for some reason the true/except block also triggers the core dump immediately, otherwise it takes a few calls to car.Skeleton):

```
import numpy as np
from skan import csr

X = np.array([1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1]).astype(bool)
try:
     S = csr.Skeleton(X)
except Exception as E:
     print(E)

```

**Comment by jni** [comment]
Yikes, good catch. Thank you for the thorough report!

> the correction calculation should be

Do you mean `np.maximum` rather than `np.max`?

```
In [1]: np.max([0, 9, -2, 0, 9], 0)
Out[1]: 9

In [2]: np.maximum([0, 9, -2, 0, 9], 0)
Out[2]: array([0, 9, 0, 0, 9])
```

Anyway, would you be able to/like guidance creating a pull request with a fix and a test? 🙏

**Comment by ssavary** [comment]
> Do you mean np.maximum rather than np.max?

Yes you are right! np.maximum is the right one.
