### ISSUE TITLE
Does numpydoc need to be an install_requires dependency?

### ISSUE THREAD

**Issue by rly** [jni/skan#186]
I work on a package that uses `skan` and am trying to reduce the dependencies that are installed. I see that `setup.cfg` specifies that installing `skan` requires the `numpydoc` package: 
https://github.com/jni/skan/blob/main/setup.cfg#L54

`numpydoc` does not seem to be important for using `skan`. Does it need to be under `install_requires`? Can it be moved to the `docs` key of the `[options.extras_require]` section below?

Interestingly, the version of `skan` on conda-forge does not require `numpydoc`:
https://github.com/conda-forge/skan-feedstock/blob/main/recipe/meta.yaml

**Comment by jni** [comment]
Oops! Yes that seems to be an oversight. I'm not sure why it went there in the first place rather than [docs]. Would you like to/be able to submit a PR fixing this? Thank you! 🙏

**Comment by rly** [comment]
I just looked a little more closely at this and realized that `numpydoc` does not seem to be used at all. In https://github.com/jni/skan/commit/2f806e71841986bac00dec1d38641f0e9067355b, the last reference to numpydoc was removed from the codebase. Should it just be removed? I also see that it is not in any of the requirements files: https://github.com/jni/skan/tree/main/requirements

**Comment by jni** [comment]
😂 yup! Thank you for spotting all these oversights. 🤦
