### ISSUE TITLE
0.11.0 release?

### ISSUE THREAD

**Issue by rly** [jni/skan#191]
The last release 0.10.0 was over a year ago and there have been 18 commits to main since then. As I maintain a package that uses `skan`, I would appreciate a new release so that I do not need to pip install from the github source to get the updates.

Thanks!!

**Comment by jni** [comment]
Thanks for the prompt! I've pushed a release candidate, which should be available on PyPI with `pip install --pre skan`, or `pip install skan==0.11.0rc2` (don't ask 😂). If you tell me everything is all right on your end I'll change the version to 0.11.0 and push the official release! 🥳

**Comment by jni** [comment]
(Release notes at: https://skeleton-analysis.org/dev/misc/release-notes/release-v0.11.0.html)

**Comment by jni** [comment]
@rly this is now released and available on PyPI and (shortly) [on conda-forge](https://github.com/conda-forge/skan-feedstock/pull/18). I'm updating the `/stable` symlink in the docs as we speak. 😊
