### ISSUE TITLE
Pending Deprecation in Numba 0.57.0.

### ISSUE THREAD

**Issue by erberj** [jni/skan#207]
https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-the-numba-pycc-module

**Comment by jni** [comment]
@erberj have you come across this warning while using numba? We don't use pycc directly anywhere in the numba code, and running pytest on the test suite doesn't (as far as I can tell) raise this warning with numba=0.57...

**Comment by erberj** [comment]
> @erberj have you come across this warning while using skan? We don't use pycc directly anywhere in the skan code, and running pytest on the test suite doesn't (as far as I can tell) raise this warning with numba=0.57...

I saw, that skan depends on numba and got this warning, wenn building an exe (containing numba and skan) with pyinstaller
