### ISSUE TITLE
path_lengths seems uncessarily slow for 2d Euclidean distance

### ISSUE THREAD

**Issue by jarodhanko-crafco** [jni/skan#209]
This may be specific to my machine or test images but the following seems to be 20-100x faster. With one specific test image, path_lengths() takes 0.6s on my machine and the below takes 0.006s. I'm not sure if it will generalize. My image is roughly 5000x3000.

```
skan_skeleton = Skeleton(skel_image, keep_image=True)

n_paths = skan_skeleton.n_paths

# path_lengths = skan_skeleton.path_lengths()

def sum_of_distances(coords):  
    coords = np.array(coords)
    differences = np.diff(coords, axis=0)
    distances = np.linalg.norm(differences, axis=1)
    return np.sum(distances)

def sum_of_distances2(coords):  
    # this works too, not sure which is generally faster
    return np.sqrt(np.sum((np.diff(coords, axis=0)**2), axis=1)).sum()

path_lengths = []
for i in range(n_paths):
    coords = skan_skeleton.path_coordinates(i)
    length = sum_of_distances(coords)
    path_lengths.append(length)
```

**Comment by jni** [comment]
Thanks for the report @jarodhanko-crafco! It's certainly possible that this is faster. Do you think you could write a complete example with an example image and built-in timings? That will make it easier for me to investigate. 🙏 

The [`bench_skan.py`](https://github.com/jni/skan/blob/95827205fe82d2995221fede6db09839ee6fd7b0/benchmarks/bench_skan.py) file might be a nice place to start — it might be as simple as adding your functions and timing them in addition to iterating over path lengths in the Skeleton object.

**Comment by jarodhanko-crafco** [comment]
@jni This is non-issue. I was only testing a single execution, which has numba overhead. Subsequent timings are equivalent or faster. Sum_of_distances2 might be marginally faster in some instances, but not much.
