### ISSUE TITLE
Standardise package configuration on pyproject.toml

### ISSUE THREAD

**Issue by ns-rse** [jni/skan#213]
The Python Packaging Authority (PyPA) is standardising on using `pyproject.toml` for package configuration[^1][^2] rather than `setup.cfg` and/or `setup.py`.

It should be fairly straight-forward to port the existing configuration from `setup.cfg` to `pyproject.toml`. At the same time [`setuptools_scm`](https://github.com/pypa/setuptools_scm) could be employed to automate versioning based on Git Tags, in turn releases to PyPI could then be automated with a GitHub workflow in a similar manner to how GitHub releases are built (separate issue).

Happy to take on the work for this @jni if you think its something worth doing.

[^1]: [PEP621 – Storing project metadata in pyproject.toml](https://peps.python.org/pep-0621/)
[^2]: [Packaging Python Projects](https://packaging.python.org/en/latest/tutorials/packaging-projects/)

**Comment by jni** [comment]
I'm definitely into this! It looks like you've already done all or most of the work, but for reference I just came across this project:

https://github.com/diazona/setuptools-pyproject-migration

**Comment by jni** [comment]
Closed by #216, #217
