### ISSUE TITLE
SKAN Skeleton not compatible with numpy 2.0

### ISSUE THREAD

**Issue by erberj** [jni/skan#228]
After upgrading to numpy 2.0 I get the following error. numpy 1.26.4 works
Best Regards
Jakob 

g = Skeleton(skeleton)
        ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jakob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\skan\csr.py", line 504, in __init__
    if np.issubdtype(skeleton_image.dtype, np.float_):
                                           ^^^^^^^^^
  File "C:\Users\jakob\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\__init__.py", line 411, in __getattr__
    raise AttributeError(
AttributeError: `np.float_` was removed in the NumPy 2.0 release. Use `np.float64` instead.

**Comment by jni** [comment]
Thanks for the report @erberj! We're gearing up for a new release, I'll make sure it's compatible by the next release. 🙏

**Comment by matthewdeancooper** [comment]
I have corrected this issue locally by making the following substitution in `skan\csr.py` on line `504`.

```
if np.issubdtype(skeleton_image.dtype, np.float_):
```
to
```
if np.issubdtype(skeleton_image.dtype, float):
```
Happy to do a PR if nobody has looked at this yet.

**Comment by jni** [comment]
I think that is also frowned upon in numpy-land @matthewdeancooper. I think the right call is:

```
if np.issubdtype(skeleton_image.dtype, np.floating):
```

I just tested it and it works for all three float dtypes (16, 32, 64).

A PR would be most welcome! 🙏

**Comment by jni** [comment]
Huh, it's interesting that ruff *does not* find this error, but it finds an alternate one:

```
$ ruff check --select NPY201 src/**
src/skan/_testdata.py:29:13: NPY201 [*] `np.row_stack` will be removed in NumPy 2.0. Use `numpy.vstack` instead.
Found 1 error.
[*] 1 fixable with the `--fix` option.
```

So *extra* thanks for the report!

**Comment by jni** [comment]
oh wait, it didn't find it because it's already fixed on main 😂 

https://github.com/jni/skan/blob/b703cf603f34bff03971cfce1d156f0160206a23/src/skan/csr.py#L525

**Comment by jni** [comment]
wow, something else ruff missed:

```
 E   AttributeError: module 'numpy' has no attribute 'VisibleDeprecationWarning'
```
