### ISSUE TITLE
numpy 2.0-compatible skan package not on PyPI

### ISSUE THREAD

**Issue by GuillaumeLeGoc** [jni/skan#230]
Hi,
First and foremost, thanks a lot for this package.

I just got a bunch of errors with numpy 2.0 with skan 0.11.1. I see that numpy 2 compatibility was added in https://github.com/jni/skan/pull/229, but it seems it was not published on PyPI.
I'm working on something that will require skan as a dependency and was wondering if you were planning to make a release, and if so, with what timeline ? To see if I need to pin numpy to <2 in my project.

Cheers,
Guillaume

**Comment by GuillaumeLeGoc** [comment]
Additional note :
I installed the current git version with `pip install git+https://github.com/jni/skan.git`, using `Skeleton` and `summarize` (with `separator="_"` to avoid warnings) worked as intended 😄

**Comment by jni** [comment]
Ach, yeah, sorry @GuillaumeLeGoc, I have been trying to get #214 past the finish line, but it's stuck on a bug I couldn't figure out, and haven't had time to revisit since the last time I played with it.

I'll just push out a release tomorrow without it, and pruning will have to wait for the next one.

Thanks for the prod, sorry for the wait, and thank you for your interest in skan! 😊

**Comment by GuillaumeLeGoc** [comment]
Alright, thanks for your reply. And good luck for the iterative pruning !

**Comment by jni** [comment]
Ach, sorry, I'm travelling and this once again fell off the plate 😅, thanks for the prod, will push ASAP!

**Comment by jni** [comment]
@GuillaumeLeGoc the pre-release version 0.12.0rc2 is out on PyPI for testing. You can test it with `pip install skan==0.12.0rc2` or `pip install -U --pre skan`. The release notes are at https://skeleton-analysis.org/dev/misc/release-notes/release-v0.12.html. Please let me know if it's all working for you and I'll push the actual release!

**Comment by GuillaumeLeGoc** [comment]
Hi, thanks for the RC !
My usage is fairly simple, I skeletonize a binary image with scikit-image `morphology.skeletonize`, remove small objects with `morphology.remove_small_objects`, and instantiate `skan.Skeleton`. Then, from `skan.summarize(skeleton, separator="_")`, I collect each branches `path_coordinates` in `shapely.LineString` objects, to finally store them with `geojson.Feature` and `geojson.FeatureCollection`.

With `skan` 0.12.0rc2, I was able to generate identical geojson files as with the previous version, so all is good for me, cheers !
Let me know if you want me to run other tests.

**Comment by jni** [comment]
> Let me know if you want me to run other tests.

Nope, that's all good, with smaller projects I go with just-in-time user testing, meaning as long as it works for you I'm happy to push, and if anything else is broken I'll fix as other users complain. 😅

0.12 is out now on PyPI, and should be out on conda-forge in ~24h. Happy coding, and do let me know if you run into other issues!

**Comment by GuillaumeLeGoc** [comment]
Nice philosophy 😄 
Thanks a lot for your responsiveness, cheers !
