### ISSUE TITLE
Version switcher and doc title aren't updating

### ISSUE THREAD

**Issue by jni** [jni/skan#233]
Switching to 0.12.x works but the title and version shown on the switcher remain at 0.11.x.

**Comment by jni** [comment]
Nope, #237 didn't fix this, nor fc01989.

Not sure what's going wrong here. Here is the current conf.py:

https://github.com/jni/skan/blob/fc0198968576672d0c2f336291d4cbabe6312f73/doc/conf.py#L129-L130

and the relevant parts of the version_switcher.json:

https://github.com/jni/skan/blob/779cbf0726b8b4665cbd66269442fbc9c534e97e/dev/_static/version_switcher.json#L7-L17

To me, they seem identical to the napari conf:

https://github.com/napari/docs/blob/e192a22c7a93940e5ac73d094e67411b07c1c04b/docs/conf.py#L94-L100

and version_switcher.json:

https://github.com/napari/docs/blob/e192a22c7a93940e5ac73d094e67411b07c1c04b/docs/_static/version_switcher.json#L7-L17

But the webpage still shows 0.11.x:

<img width="994" alt="Screenshot 2024-11-22 at 6 36 03 PM" src="https://github.com/user-attachments/assets/a7af20c4-bf96-43e5-bb95-3324cc9ce945">

@melissawm @lucyleeow sorry to draw you into a "side" project but I'm wondering if either of you can see something obvious I'm missing here??? 😵‍💫

**Comment by melissawm** [comment]
Can you confirm that version_match is returning the right version?

**Comment by jni** [comment]
... ... ... 😅 

🙏!!!
