### ISSUE TITLE
sk.csr.Skeleton and sk.csr.summarise indices don't match

### ISSUE THREAD

**Issue by tensionhead** [jni/skan#71]
We have an example here, where the summarise method lists the longest branch with index 0, the sk.csr.Skeleton.path_coordinates however have different ordering, it's actually index 1 to get the coordinates of the longest branch. I attach an example, it's a zipped tif.
[example_skel.zip](https://github.com/jni/skan/files/3211184/example_skel.zip)

**Comment by jni** [comment]
Hi @tensionhead and thanks for reporting!

I will investigate tomorrow, but just quickly: are you using the released version, or the master version from git? I fixed an indexing order bug in #65, but haven't yet made a release with those changes! I'll try to push a release in the coming days.

If you're comfortable installing the version on master, please try that and tell me whether it also has different indexing order.

**Comment by tensionhead** [comment]
Hi @jni , thanks for your quick reply! I installed skan with
`pip3 install git+https://github.com/jni/skan` 
which I guess gives me the master version? If not I can happily test it by cloning your repo locally, just let me know.

**Comment by jni** [comment]
That's the master version all right. =) Let me have a look to see whether I can make them consistent, then push out a new release. =)

**Comment by jni** [comment]
@tensionhead so, after examining the code, I decided that the `summarise` and `csr.Skeleton` code had diverged too much to reconcile. Instead what I've done is create a new `summarize` function that takes a Skeleton as input and provides the same output as `summarise` but in order consistent with the input skeleton. This is done in #72 and now in master. Could you update and let me know whether it fulfills your needs?

**Comment by jni** [comment]
> Maybe then it's good to ditch the old summarise all together?

Yes, I will add a bunch of deprecations in this release, and remove them in the next one.

> In the meantime, we just manually looped over the Skeleton.path_coordinates and picked the longest

Ok! Let me know if you find any more rough edges in the API! Also, if/when you publish something, please consider adding an entry with your data to the docs! I'd like to show off the diversity of applications suited for skeleton analysis. =)

**Comment by tensionhead** [comment]
Hello,

sorry for the late reply!

> Ok! Let me know if you find any more rough edges in the API!
>
Will do, but so far we are quite happy now.


> Also, if/when you publish something, please consider adding an entry with
> your data to the docs! I'd like to show off the diversity of applications
> suited for skeleton analysis. =)
>
What kind of docs do you mean? If we publish the results eventually, we
make sure to acknowledge your repo accordingly! Right now we do classical
image analysis of life imaged fluorescently labeld fish, and we need to
automatically segment the body axis mid line. This is where skan is doing a
fantastic job for us, so we don't need to go back to ImageJ ;)

**Comment by jni** [comment]
> What kind of docs do you mean?

[This page](https://jni.github.io/skan/complete_analysis.html) in the documentation reproduces the analysis that we did for the [paper](https://peerj.com/articles/4312/) (for which we would definitely appreciate a citation!). It is actually generated from a [notebook](https://github.com/jni/skan/blob/master/doc/complete_analysis.ipynb) in the repo. Once you've published, it would be super cool to get a second notebook with your data!
