### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by qiang-zhang-neu** [jni/skan#76]
error happened when I import skan

environment:
win10
python 3.5.6
skan-0.8

error information:

>>> import skan
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\ProgramData\Anaconda3\envs\general\lib\site-packages\skan\__init__.py", line 1, in <module>
    from .csr import skeleton_to_csgraph, branch_statistics, summarize, Skeleton
  File "D:\ProgramData\Anaconda3\envs\general\lib\site-packages\skan\csr.py", line 485
    summary[f'image-coord-src-{i}'] = skel.coordinates[endpoints_src, i]
                                 ^
SyntaxError: invalid syntax

**Comment by jni** [comment]
@qiang-zhang-neu I'm afraid skan only works with Python 3.6 and above. So this is expected, and you should upgrade your Python version to continue to use skan.

I *don't* think that you should have been able to install it without error though. I'll leave this issue open until I can fix the installation process. Thanks for reporting!

**Comment by qiang-zhang-neu** [comment]
Thank you for the reply. 

Actually, the install is OK.

**Comment by jni** [comment]
Thanks @qiang-zhang-neu! Well, it should not have been possible to install it on an unsupported Python version...
