### ISSUE TITLE
Obtain path IDs on a branch

### ISSUE THREAD

**Issue by CsatiZoltan** [jni/skan#82]
I tested *skan* on one of your test data (see screenshot below). I would like to obtain the node IDs for a given branch. In this case, 

| branch | end points | path IDs I want  |
| ------ | ---------- | -------------------------- |
| 0      | (8,13)     | (13,10,11,7,5,4,3,2,1,6,8) |
| 1      | (8,13)     | (8,9,13)                   |
| 2      | (8,14)     | (8,12,14)                  |
| 3      | (13,17)    | (13,15,16,17)          |

I checked the attributes of the **Skeleton** class, but I can't find this information.

![skan](https://user-images.githubusercontent.com/12742890/81294349-0c477280-906f-11ea-85c8-54037752e405.png)

**Comment by jni** [comment]
Thanks for your interest in skan, @CsatiZoltan! You simply need the `path(i)` method:

https://jni.github.io/skan/api/skan.csr.html#skan.csr.Skeleton.path

Hope this helps! Please reopen if it is not what you were looking for!

**Comment by CsatiZoltan** [comment]
Perfect! Thank you for the quick response. My bad, somehow I didn't notice the `path` method.
