### ISSUE TITLE
Get full Branch Information

### ISSUE THREAD

**Issue by fachstetter** [jni/skan#85]
I am trying to circumvent the Fiji 'Analyse Skeleton (2D/3D)' functionality in Python and Skan seems to be the perfect project for that. I have a question regarding the Detailed Branch Information and I would very much appreciate if somebody could point me in the right direction. 

I start with an Imaris derived reconstruction of a neuron (left image). Fijis 'Analyse Skeleton (2D/3D)' function gives me a list of vectors which nicely cover the entire branch (right image).  I try to replicate this behavior through skimage.morphology.skeletonize() and skan.csr.summarise(). However, this gives me a table which only contains the junction-to-junction/end connections (middle image). Is there anyway to access the intermediate filament paths as well? 

Your input is very much appreciated 

![Fiji-Skan](https://user-images.githubusercontent.com/62266195/85723596-ae8ce980-b6f3-11ea-84e9-999453d028c1.png)

**Comment by jni** [comment]
Yes, there is! The [Skeleton class](https://jni.github.io/skan/api/skan.csr.html#skan.csr.Skeleton) contains a lot of information about branches including the full branch path, and you can draw full skeletons on a matplotlib canvas, colored by any property, using the rather poorly-named [`skan.draw.overlay_skeleton_2d_class`](https://jni.github.io/skan/api/skan.draw.html#skan.draw.overlay_skeleton_2d_class) function.

We don't have any 3D drawing capabilities yet, unfortunately.

I hope this helps!

**Comment by fachstetter** [comment]
Thank you very much! 

In case anyone is wondering: The properties can be found under Skeleton.path_coordinates(index)

Best wishes
