### ISSUE TITLE
Adding link to the conference talk

### ISSUE THREAD

**Issue by CsatiZoltan** [jni/skan#88]
As I was looking for an unrelated topic (numba), I found your [talk](https://www.youtube.com/watch?v=0pUPNMglnaE) on YouTube. I think, it would be useful to add a pointer to that video in the *skan* documentation or in the README.

**Comment by jni** [comment]
@CsatiZoltan that's a great idea! I like how dask does that, for example. I'd definitely appreciate a pull request for this if you have the time!
