### ISSUE TITLE
Where is the objects.inv file in the documentation?

### ISSUE THREAD

**Issue by CsatiZoltan** [jni/skan#91]
In my documentation, I want references to Skan classes and functions using [intersphinx](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html). For that, I need an *objects.inv* file. (see also [here](https://github.com/numpy/numpy/issues/1983)). [Related.](https://code-examples.net/en/q/1d81adb). Do you have experience on hwo to solve it? If no, don't spend time with it, not that important.

**Comment by jni** [comment]
@CsatiZoltan TIL that the `objects.inv` file for skan can be found at https://jni.github.io/skan/objects.inv! 😂 

fyi the way I figured this out is by cd-ing into `doc`, running `make html`, then checking `_build/html` and finding that there is indeed that file right there at the root of the build. =)

**Comment by CsatiZoltan** [comment]
Thanks, works perfectly. Now I know how to fetch them for other projects as well!
