### ISSUE TITLE
Documentation: visualise 2D and 3D networks in napari

### ISSUE THREAD

**Issue by jni** [jni/skan#98]
napari has support for line shapes. It should be possible to view the many different layers of a skeleton pipeline (grayscale image, binary image, skeletonised image, and skeleton with properties) in napari using a Shapes layer, or perhaps using a new layer.

Some napari references for this:

https://github.com/napari/napari/issues/693
https://napari.org/tutorials/fundamentals/shapes
https://github.com/napari/napari/blob/master/examples/3D_paths.py

**Comment by jni** [comment]
This script visualizes skeletons as label images:

https://github.com/jni/useful-histories/blob/master/vessel-skeleton-analysis.py

**Comment by kushaangupta** [comment]
Hi! I hope to work on this issue but the 693 & 2662 issues in napari repository are still not yet resolved. Can I have some more guidance on this?

**Comment by jni** [comment]
Hi @kushaangupta! To do this properly with Shapes probably requires some work on the napari side. For now, I think we should work using label images, see the script above and also https://github.com/kevinyamauchi/napari-skeleton-curator/tree/main/examples. Actually some people in my group are working on this stuff so it would be good to coordinate with them.

CC @thanushipeiris @lucyleeow @jamesryan094

**Comment by jni** [comment]
This was closed by #155! 🎉 In the future we can keep improving that documentation.
